### ISSUE TITLE
Ajout d'icônes

### ISSUE THREAD

**Issue by jgribonvald** [GIP-RECIA/icons-pack#1]
Merci de créer des icônes personnalisées pour les services suivants:
```
ActualitesDRAAF.svg
ActualitesRectorat.svg
DocumentsDRAAF.svg
DocumentsRectorat.svg
```

Rien ne presse pour le moment le service est publié mais pas encore utilisé, et j'ai recopié l'icône d'un service identique. Mais il manque la personnalisation par rapport au contexte (rectorat = EN, DRAAF = monde Agricole)

**Comment by gbrousse-recia** [comment]
ActualitesDRAAF.svg  : feat: add  ActualitesDRAAF #1751597a3db3e8ee74102056d817e870302ca4f1
ActualitesRectorat.svg  : feat: add  ActualitesRectorat #43e07e0d1770b8755c9a508258723419aadb8dfe
DocumentsDRAAF.svg  : feat: add  DocumentsDRAAF #56a71ce20a5333c79f5d61dac32930a1b6138601
DocumentsRectorat.svg  : feat: add  DocumentsRectorat #1153cbe206b99dd5aa9923e859f127a5c6887374
@jgribonvald, ca te va ?

**Comment by jgribonvald** [comment]
@gbrousse-recia 
Merci !
j'aime beaucoup celui de la DRAAF avec l'épi de blé ;) Pour le rectorat ça reste un grand classique, mais il n'y a pas mieux à ma connaissance
